server:
  port: 8630
  servlet:
    session:
      # 配置会话超时
      timeout: 120s
spring:
  application:
    name: SpringAI
  ai:
    ollama:
#      base-url: http://192.168.1.6:11434
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
logging:
  level:
    org:
      springframework:
        web: DEBUG
      apache:
        http: DEBUG
